language: objective-c
osx_image: xcode8.3

xcode_sdk:
- iphonesimulator10.3

xcode_workspace: JSONModelKit.xcworkspace

jobs:
  include:
    - script: xcodebuild -workspace ExtendaBLE.xcworkspace -scheme ExtendaBLE-iOS -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 7,OS=10.3.1' test
